print("welcome to the love calculator: ")
m = input("pls enter your name(boy) : ")
f = input("pls enter your name(girl) : ")
m_new=m.lower()
f_new=f.lower()
t = m_new.count("t") + f_new.count("t")
print(f"T occurs {t} times")
r = m_new.count("r") + f_new.count("r")
print(f"R occurs {r} times")
u =m_new.count("u") + f_new.count("u")
print(f"U occurs {u} times")
e_1 = m_new.count("e") + f_new.count("e")
print(f"E occurs {e_1} times")
l = m_new.count("l") + f_new.count("l")
print(f"L occurs {l} times")
o = m_new.count("o") + f_new.count("o")
print(f"O occurs {o} times")
v = m_new.count("v") + f_new.count("v")
print(f"V occurs {v} times")
e = m_new.count("e") + f_new.count("e")
print(f"E occurs {e} times")
total_score = int(str(t+r+u+e_1)+str(l+o+v+e))
# print(f"your total love would be {total_score}%")
if 10 < total_score < 90:
    print("according to your total score you will go like coke and Mentos 🤣. ")
elif 40 < total_score < 50:
    print("according to your total score you are alright together ❤. ")
else:
    print(total_score)